"""
Chapter 6's test suite: document ingestion (PDF/DOCX -> real Chunk objects).

Run with:  pytest tests/test_document_ingestion.py -v

Unlike tests/test_contract.py (whose fixtures are HAND-WRITTEN, by design —
see that file's own docstring), most of Part 4 below runs the real pipeline
against the real files in data/documents/, generated by
scripts/generate_sample_corpus.py. This is deliberate: Chapter 5's closing
line promised "the first pipeline that actually produces a Chunk from a
real PDF... against real, not hand-written, data" — this file is that
promise, kept.

If you edit scripts/generate_sample_corpus.py's page text, several exact
assertions below (word counts, chunk counts, specific phrases) will need
updating too — they are pinned to the corpus text on purpose, not
coincidentally passing.
"""

import sys
from pathlib import Path

import pytest

# Same no-packaging-ceremony import trick as test_contract.py.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.core.config import settings
from src.core.schemas import TEXT_COLLECTION, validate_chunk
from src.core.text_normalize import normalize_text
from src.pipelines.documents.chunker import chunk_page_text
from src.pipelines.documents.docx_parser import extract_docx_pages
from src.pipelines.documents.ingest import ingest_document

NOTICE = "data/documents/notice.pdf"
LIBRARY_HOURS = "data/documents/library_hours.pdf"
IT_ONBOARDING = "data/documents/it_onboarding.docx"


# ---------------------------------------------------------------------------
# Part 1 — normalize_text: a pure function's edge cases
# ---------------------------------------------------------------------------

def test_normalize_text_collapses_whitespace():
    assert normalize_text("Hello\n\n\tworld  again") == "Hello world again"


def test_normalize_text_strips_control_characters():
    # \x00 (NUL) and \x1f (unit separator) and \x7f (DEL) are not
    # whitespace — they must be removed outright, per
    # reports/methodology-draft.md §3.1's "control characters removed".
    assert normalize_text("Hello \x00world \x1fagain\x7f") == "Hello world again"


def test_normalize_text_handles_empty_and_whitespace_only_input():
    assert normalize_text("") == ""
    assert normalize_text("   \n\t  ") == ""


# ---------------------------------------------------------------------------
# Part 2 — chunk_page_text: the sliding-window algorithm, isolated from
# Chunk/settings entirely (see chunker.py's own docstring for why)
# ---------------------------------------------------------------------------

def test_chunker_short_page_is_one_chunk():
    text = " ".join(f"w{i}" for i in range(50))
    chunks = chunk_page_text(text, size_words=300, overlap_words=50)
    assert len(chunks) == 1
    assert chunks[0] == text


def test_chunker_produces_overlapping_windows_for_a_long_page():
    text = " ".join(f"w{i}" for i in range(620))
    chunks = chunk_page_text(text, size_words=300, overlap_words=50)
    assert [len(c.split()) for c in chunks] == [300, 300, 120]
    # The overlap contract: chunk N's last 50 words == chunk N+1's first 50.
    for a, b in zip(chunks, chunks[1:]):
        assert a.split()[-50:] == b.split()[:50]


def test_chunker_merges_short_tail_into_previous_chunk():
    # 305 words: a naive implementation emits a second chunk of 5 new words
    # sitting on top of 50 duplicated ones. The tail-merge rule folds it
    # into chunk one instead — see chunker.py §"Tail-merge rule".
    text = " ".join(f"w{i}" for i in range(305))
    chunks = chunk_page_text(text, size_words=300, overlap_words=50)
    assert len(chunks) == 1
    assert len(chunks[0].split()) == 305


def test_chunker_rejects_overlap_not_smaller_than_size():
    with pytest.raises(ValueError):
        chunk_page_text("a b c", size_words=100, overlap_words=100)


def test_chunker_empty_text_produces_no_chunks():
    assert chunk_page_text("", size_words=300, overlap_words=50) == []


# ---------------------------------------------------------------------------
# Part 3 — DOCX page-break detection, isolated (tiny in-memory docs built
# with python-docx itself, so this doesn't depend on the generated corpus)
# ---------------------------------------------------------------------------

def test_docx_parser_detects_run_level_page_break(tmp_path):
    from docx import Document
    doc = Document()
    doc.add_paragraph("Page one text")
    doc.add_page_break()  # <w:br w:type="page"/> inside its own paragraph
    doc.add_paragraph("Page two text")
    path = tmp_path / "run_break.docx"
    doc.save(path)

    pages = extract_docx_pages(path)
    assert [p for p, _ in pages] == [1, 2]
    assert pages[0][1] == "Page one text"
    assert pages[1][1] == "Page two text"


def test_docx_parser_detects_page_break_before_property(tmp_path):
    from docx import Document
    doc = Document()
    doc.add_paragraph("Page one text")
    para = doc.add_paragraph("Page two text")
    para.paragraph_format.page_break_before = True
    path = tmp_path / "before_break.docx"
    doc.save(path)

    pages = extract_docx_pages(path)
    assert [p for p, _ in pages] == [1, 2]
    assert pages[0][1] == "Page one text"
    assert pages[1][1] == "Page two text"


def test_docx_parser_reports_single_page_when_no_breaks_exist(tmp_path):
    from docx import Document
    doc = Document()
    doc.add_paragraph("First paragraph")
    doc.add_paragraph("Second paragraph")
    path = tmp_path / "no_break.docx"
    doc.save(path)

    pages = extract_docx_pages(path)
    assert [p for p, _ in pages] == [1]
    assert pages[0][1] == "First paragraph\nSecond paragraph"


# ---------------------------------------------------------------------------
# Part 4 — the actual point of this chapter: the real pipeline against the
# real generated corpus (data/documents/, from
# scripts/generate_sample_corpus.py), not hand-written fixtures.
#
# If these fail with FileNotFoundError, run:
#   python scripts/generate_sample_corpus.py
# ---------------------------------------------------------------------------

def test_every_real_chunk_satisfies_the_contract():
    for path in (NOTICE, LIBRARY_HOURS, IT_ONBOARDING):
        for chunk in ingest_document(path):
            errors = validate_chunk(chunk)
            assert errors == [], f"{path} produced an invalid chunk: {errors}"


def test_chunk_ids_are_unique_per_file():
    for path in (NOTICE, LIBRARY_HOURS, IT_ONBOARDING):
        chunks = ingest_document(path)
        ids = [c.chunk_id for c in chunks]
        assert len(ids) == len(set(ids)), f"{path} produced duplicate chunk_ids: {ids}"


def test_chunk_id_format_matches_convention():
    # Would fail immediately against a `.stem`-based implementation, since
    # `Path("notice.pdf").stem` drops the extension entirely.
    chunks = ingest_document(NOTICE)
    assert chunks[0].chunk_id == "notice_pdf__p1__c001"


def test_chunk_never_spans_a_page_boundary():
    chunks = ingest_document(NOTICE)
    page1_text = " ".join(c.text for c in chunks if c.page == 1)
    page2_text = " ".join(c.text for c in chunks if c.page == 2)
    # "Guide allocation" only appears on page 1; "mid-term evaluation" only
    # on page 2 (see scripts/generate_sample_corpus.py's NOTICE_P1/P2).
    assert "Guide allocation" in page1_text
    assert "Guide allocation" not in page2_text
    assert "mid-term evaluation" in page2_text
    assert "mid-term evaluation" not in page1_text


def test_notice_page_two_produces_two_overlapping_chunks():
    # NOTICE_P2 is exactly 380 words on purpose (Chapter 6 §3.2) — with
    # CHUNK_SIZE_WORDS=300/CHUNK_OVERLAP_WORDS=50 that's [0,300] + [250,380].
    chunks = [c for c in ingest_document(NOTICE) if c.page == 2]
    assert len(chunks) == 2
    assert [len(c.text.split()) for c in chunks] == [300, 130]


def test_notice_pdf_contains_the_day5_fixture_sentence_verbatim():
    # tests/test_contract.py's HAND-WRITTEN text_fixture invented this
    # exact sentence on Day 5, before this file existed. Today it's real.
    chunks = [c for c in ingest_document(NOTICE) if c.page == 2]
    combined = " ".join(c.text for c in chunks)
    assert "The submission deadline for the project synopsis is 21st August." in combined


def test_library_hours_pdf_produces_exactly_one_chunk():
    chunks = ingest_document(LIBRARY_HOURS)
    assert len(chunks) == 1


def test_docx_page_break_is_detected_end_to_end():
    chunks = ingest_document(IT_ONBOARDING)
    pages_seen = sorted(set(c.page for c in chunks))
    assert pages_seen == [1, 2]
    page1_text = " ".join(c.text for c in chunks if c.page == 1)
    page2_text = " ".join(c.text for c in chunks if c.page == 2)
    assert "RAGNOVA-STUDENT" in page1_text
    assert "suspended" in page2_text


def test_embedding_model_field_matches_settings():
    for path in (NOTICE, LIBRARY_HOURS, IT_ONBOARDING):
        for chunk in ingest_document(path):
            assert chunk.embedding_model == settings.TEXT_EMBEDDING_MODEL


def test_source_field_uses_forward_slashes_and_matches_convention():
    chunks = ingest_document(NOTICE)
    assert chunks[0].source == "data/documents/notice.pdf"


def test_modality_field_matches_file_extension():
    assert ingest_document(NOTICE)[0].modality == "pdf"
    assert ingest_document(IT_ONBOARDING)[0].modality == "docx"


# ---------------------------------------------------------------------------
# Part 5 — orchestrator error handling
# ---------------------------------------------------------------------------

def test_ingest_document_rejects_unsupported_extension(tmp_path):
    fake = tmp_path / "notes.txt"
    fake.write_text("hello")
    with pytest.raises(ValueError):
        ingest_document(fake)


def test_ingest_document_missing_file_raises_file_not_found():
    with pytest.raises(FileNotFoundError):
        ingest_document("data/documents/does_not_exist.pdf")


def test_blank_pdf_page_produces_zero_chunks_and_warns(tmp_path, capsys):
    # Chapter 6 §1.4's policy, exercised for real rather than only asserted
    # in prose: a page with zero extractable text (here, a genuinely blank
    # page — the simplest real example, same underlying case as a scanned
    # page with no text layer) is warned about and skipped, not an error.
    # This exact path went unexercised by any test until Chapter 7's own
    # verification process ran it manually and found the warning's em-dash
    # was being mangled on an unconfigured Windows console — see ingest.py's
    # `sys.stderr.reconfigure` for the fix this test also guards.
    fitz = pytest.importorskip("fitz", reason="PyMuPDF not installed yet")
    doc = fitz.open()
    doc.new_page()
    blank = tmp_path / "blank.pdf"
    doc.save(blank)
    doc.close()

    chunks = ingest_document(blank)
    assert chunks == []

    warning = capsys.readouterr().err
    assert "no extractable text" in warning
    assert "—" in warning  # confirms the em-dash survived, not "?" or "�"


# ---------------------------------------------------------------------------
# Part 6 — round-trip REAL chunks through ChromaDB, same pattern as
# test_contract.py's test_round_trips_through_chromadb, but sourced from
# ingest_document() instead of a hand-written fixture.
# ---------------------------------------------------------------------------

def test_real_chunks_round_trip_through_chromadb(tmp_path):
    chromadb = pytest.importorskip("chromadb", reason="chromadb not installed yet")

    client = chromadb.PersistentClient(path=str(tmp_path / "chroma_test"))
    text_col = client.get_or_create_collection(TEXT_COLLECTION)

    chunks = ingest_document(NOTICE)
    for chunk in chunks:
        rec = chunk.to_chroma_record()
        text_col.add(ids=[rec["id"]], documents=[rec["document"]],
                      metadatas=[rec["metadata"]], embeddings=[[0.0] * 384])

    got = text_col.get(ids=[c.chunk_id for c in chunks], include=["documents", "metadatas"])
    assert set(got["documents"]) == {c.text for c in chunks}
    assert all(m["source"] == "data/documents/notice.pdf" for m in got["metadatas"])
